export {default as Contact} from './Contact'
export {default as Mission} from './Mission'
export {default as Problem} from './Problem'
export {default as Solution} from './Solution'
export {default as Team} from './Team'
export {default as Welcome} from './Welcome'
export {default as Supporters} from './Supporters'
export {default as Friends} from './Friends'